[package]
name = "basic_read"
edition = "2021"
publish = false

[dependencies]
cortex-m-rt = "0.7.0"
cortex-m = {version = "0.7.0", features = ["critical-section-single-core"]}
panic-semihosting = "0.6.0"
defmt = "0.3.10"
defmt-rtt = "0.4.1"
nrf52840-hal= "0.18.0"
bmi2 = { path = "../../../" }
